/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GimnasioGrupo10.VISTAS;

import GimnasioGrupo10.ACCESO_A_DATOS.ClaseData;
import GimnasioGrupo10.ACCESO_A_DATOS.EntrenadorData;
import GimnasioGrupo10.ENTIDADES.Clase;
import GimnasioGrupo10.ENTIDADES.Entrenador;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

public class FormClase extends javax.swing.JInternalFrame {

    private ClaseData claseData;
    private EntrenadorData entrenadorData = new EntrenadorData();

    private Clase clas = null;
    private ArrayList<Entrenador> listaE = entrenadorData.listarEntrenadoresActivos();

    public FormClase() {
        initComponents();
        cargarHorarios();
        cargarEntrenadores();
        claseData = new ClaseData();
        jcbEntrenador.setSelectedIndex(-1);
        jcbHorario.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlClase = new javax.swing.JLabel();
        jrbEstado = new javax.swing.JRadioButton();
        jlEstado = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jlHorario = new javax.swing.JLabel();
        jtCapacidad = new javax.swing.JTextField();
        jlCapacidad = new javax.swing.JLabel();
        jlDNIEntrenador = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jbNuevo = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jcbHorario = new javax.swing.JComboBox<>();
        jcbEntrenador = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("CLASES");
        setPreferredSize(new java.awt.Dimension(480, 471));

        jlClase.setFont(new java.awt.Font("Dubai Medium", 3, 18)); // NOI18N
        jlClase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlClase.setText("ALTA - CLASE");

        jrbEstado.setText("Activo");

        jlEstado.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlEstado.setText("Estado");

        jlHorario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlHorario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlHorario.setText("Horario");

        jlCapacidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlCapacidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCapacidad.setText("Capacidad");

        jlDNIEntrenador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlDNIEntrenador.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlDNIEntrenador.setText("Entrenador");

        jlNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlNombre.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlNombre.setText("Nombre");

        jbNuevo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbNuevo.setText("Nuevo");
        jbNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbNuevoMouseClicked(evt);
            }
        });
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });

        jbGuardar.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbSalirMouseClicked(evt);
            }
        });

        jcbHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbHorarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlClase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlDNIEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlCapacidad)
                                    .addComponent(jlEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jbNuevo)
                                .addGap(46, 46, 46)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtNombre)
                                .addComponent(jcbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcbEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbGuardar)
                                    .addComponent(jrbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jlClase, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDNIEntrenador)
                    .addComponent(jcbEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlHorario)
                    .addComponent(jcbHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCapacidad))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEstado)
                    .addComponent(jrbEstado))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevo)
                    .addComponent(jbGuardar)
                    .addComponent(jbSalir))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbSalirMouseClicked
        dispose();
    }//GEN-LAST:event_jbSalirMouseClicked

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        limpiarCampos();
        jcbEntrenador.setSelectedIndex(-1);
        jcbHorario.setSelectedIndex(-1);
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jcbHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbHorarioActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

        try {
            if (jtNombre.getText().isEmpty() || jcbEntrenador.getSelectedIndex() == -1 || jtCapacidad.getText().isEmpty()
                    || jcbHorario.getSelectedIndex() == -1) {
                JOptionPane.showMessageDialog(this, "no pueden haber campos vacios!!");
                return;
            }
            String nombre_clase = jtNombre.getText();
            Entrenador entrenador = (Entrenador) jcbEntrenador.getSelectedItem();
            Integer capacidad = Integer.parseInt(jtCapacidad.getText());
            LocalTime horario = (LocalTime) jcbHorario.getSelectedItem();
            boolean estado = jrbEstado.isSelected();

//public Clase(int id_clase, String nombre_clase, Entrenador entrenador, LocalTime hora_clase, int capacidad_clase, boolean estado_clase) {
            Clase clase = new Clase(nombre_clase, entrenador, horario, capacidad, estado);
            claseData.cargarClase(clase);
            JOptionPane.showMessageDialog(this, "clase cargada con exito");

        } catch (NumberFormatException e) {
//            JOptionPane.showMessageDialog(this,"se ingreso un numero invalido");
//            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbNuevoMouseClicked
        // TODO add your handling code here:

        jtNombre.setEnabled(true);
        jcbEntrenador.setEnabled(true);
        jcbHorario.setEnabled(true);
        jtCapacidad.setEnabled(true);
        jrbEstado.setEnabled(true);

    }//GEN-LAST:event_jbNuevoMouseClicked

    private void limpiarCampos() {
        jtNombre.setText("");
        jcbEntrenador.setSelectedIndex(0);
        jcbHorario.setSelectedIndex(0);
        jrbEstado.setSelected(false);
    }



    private void cargarHorarios() {
        // Lista de horarios disponibles

        ArrayList<LocalTime> horarios = new ArrayList<>();

        // Agregar horarios desde las 8:00 hasta las 20:00, con intervalos de una hora
        LocalTime hora = LocalTime.of(8, 0);
        while (hora.isBefore(LocalTime.of(20, 0))) {
            horarios.add(hora);
            hora = hora.plusHours(1);
        }
        for (LocalTime horario : horarios) {
            jcbHorario.addItem(horario);
        }
    }


    private void cargarEntrenadores() {
        for (Entrenador entr : listaE) {
            jcbEntrenador.addItem(entr);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JComboBox<Entrenador> jcbEntrenador;
    private javax.swing.JComboBox<LocalTime> jcbHorario;
    private javax.swing.JLabel jlCapacidad;
    private javax.swing.JLabel jlClase;
    private javax.swing.JLabel jlDNIEntrenador;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JLabel jlHorario;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtCapacidad;
    private javax.swing.JTextField jtNombre;
    // End of variables declaration//GEN-END:variables
}
